### ISSUE TITLE
Unable to run gulp tasks with node version 8 on x64 machine

### ISSUE THREAD

**Issue by ArvidBauters** [VirtoCommerce/vc-platform#1479]
Hi, 

I am unable to run the gulp tasks which copy the fonts etc. This causes us to see weird characters in the UI.

![image](https://user-images.githubusercontent.com/29769235/48905805-d3a7df00-ee62-11e8-8445-baa6811ac242.png)

What I see in the task runner explorer is this:

Failed to run "C:\...\VirtoCommerce\Platform\VirtoCommerce.Platform.Web\Gulpfile.js"...
cmd.exe /c gulp --tasks-simple
C:\...\VirtoCommerce\Platform\VirtoCommerce.Platform.Web\node_modules\node-sass\lib\binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1

Aparently gulp-sass 2.2.0 has a dependency on node sass 3.13.1. This does not support node 8, it only supports node up to v7.
Is there a possibility to update gulp-sass to 3.1.0 which depends on node sass 4.6.0 to be able to support node 8 & 9?

**Comment by ArvidBauters** [comment]
The underlying reason for this bug is that we are not able to load the ui fonts on our deployed environments. If I look at the package produced by the vsts build, these fonts are underneath the Content/fonts folder while they are referenced as being underneath Content directly. 
This reference was changed in this commit: https://github.com/VirtoCommerce/vc-platform/commit/32ae337b30cf03eecdff0fdae412aa8f3b1ded5c . I also see that the fonts are checked in underneath  both Content/fonts & Content directly, but the fonts that are directly underneath Content are not included in the project which is why they are not taken into the package.

Could we include the fonts under Content in the project? Or change the reference to these fonts to include the folder again?

**Comment by tatarincev** [comment]
The platform team will attempt to update these `npm ` dependencies.
FYI
This bug with strange char in ui-grid  is already fixed by this PR https://github.com/VirtoCommerce/vc-platform/pull/1412  and described  https://github.com/VirtoCommerce/vc-platform/issues/1409 issue.

**Comment by tatarincev** [comment]
The problem was the fonts location, and this was fixed in this PR

**Comment by ArvidBauters** [comment]
Hi,
Locally I indeed don't have this issue anymore. On our deployed environments, we still have the issue though. We are currently at platform version 2.13.37. 
We build our own packages as we also have custom modules. The packages are built by including all items that are included in the csproj file, so the fontfiles in the Content/fonts folder are included, but the fontfiles that are under Content directly are not. The allStyles.css references the fontfiles underneath the Content folder for its @font-face .  So we are getting this error:
![image](https://user-images.githubusercontent.com/29769235/49000940-701bfb00-f15b-11e8-86e0-b653785b172c.png)

What steps could we take to solve this?

**Comment by tatarincev** [comment]
Yes, seems this bug wasn't fixed. So I've included these fonts under `Content` folder and this help

**Comment by ArvidBauters** [comment]
Ok, thank you very much for following up.
When will this fix be released?

**Comment by tatarincev** [comment]
Already released 2.13.28 https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.38

**Comment by tatarincev** [comment]
@ArvidBauters  Can I close this issue?

**Comment by ArvidBauters** [comment]
Yes, you can. We will update platform to 2.13.38 to fix the icon issue
