### ISSUE TITLE
License url - page not found

### ISSUE THREAD

**Issue by jasonchester** [VirtoCommerce/vc-platform#1630]
**Describe the bug**
license URL leads to a 404 page.

linked from https://github.com/VirtoCommerce/vc-platform/blob/master/LICENSE

linked to
https://virtocommerce.com/open-source-license

![image](https://user-images.githubusercontent.com/337720/64285331-901ded80-cf29-11e9-9377-3d6d3fa6df2f.png)

**Comment by vturovets** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/20731316/64441357-681fbd00-d0d6-11e9-9a87-f5166eaa48e1.png)

![image](https://user-images.githubusercontent.com/20731316/64441406-81286e00-d0d6-11e9-86ed-b4e862539802.png)

**Comment by abdulla-tuychi** [comment]
this project seems to be not serious. Still not reachible. Is is difficult to put it on github?
